### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by shanmugam143** [LarsVoelker/FibexConverter#2]
Hi,
I tried to convert the example Some/IP FIBEX configuration file from vector to wireshark config using the Fibex Converter tool.
I got the below error

TypeError: 'NoneType' object is not subscriptable

Is it a problem with my FIBEX file ? I can't able to clearly see where is the error . The same file is working fine in the CANoe simulation.

Please have a look at the attached error log file for more information
[error.txt](https://github.com/LarsVoelker/FibexConverter/files/6660620/error.txt)

I have also attached my FIBEX file too. I attached it as text file, you can change the extension to xml if you want to try it
[FBX4_VECTOR_SOME_IP_MM.txt](https://github.com/LarsVoelker/FibexConverter/files/6660634/FBX4_VECTOR_SOME_IP_MM.txt)

**Comment by LarsVoelker** [comment]
Your example files does not have any controllers modeled, which I expected.

I pushed a small change that can live with the missing controllers. :)

https://github.com/LarsVoelker/FibexConverter/commit/57e5edb3dd49f249b550ce246baa0d61c5d5955e
