### ISSUE TITLE
Would it be possible to create github releases?

### ISSUE THREAD

**Issue by matawed** [LarsVoelker/FibexConverter#6]
I'd like to use your tool (btw. kudos for that!) in order to generate wireshark configs in order to decode SOME/IP payload. 

However, in order to use it in our build system it would be easier to reference a release of your repo (i.e. a tarball with all the sources of this release/tag) instead of a specific commit. See [docs](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) for details.

Would it be possible to create releases in this repo? For now it would be sufficient to do that once.

**Comment by vanhauser-thc** [comment]
you can clone the repo, create a realease there, and use that.

**Comment by vanhauser-thc** [comment]
if you look at the repository changes, they are minor and only other months. to put a on burden Lars every time on a change for something you need ... well, you know ... 
(and there are easy ways to auto sync forks)
