### ISSUE TITLE
module name `parser` clashes with Python standard lib module

### ISSUE THREAD

**Issue by matawed** [LarsVoelker/FibexConverter#7]
According to https://docs.python.org/3.8/library/parser.html#module-parser module name `parser` i.e. [parser.py](https://github.com/LarsVoelker/FibexConverter/blob/master/parser.py)  is already taken by Python standard lib.

Because of that statements like

https://github.com/LarsVoelker/FibexConverter/blob/34d51b0/configuration_to_wireshark_config.py#L26

might result in unexpected outcome. 
As you use `from parser import *` problem is not immediately recognized at import statement , but later on Python interpreter might complain about e.g. `name 'parse_input_files' is not defined`, because it actually used another file for this module.

See also https://chrisyeh96.github.io/2017/08/08/definitive-guide-python-imports.html#basics-of-the-python-import-and-syspath for details in which order imports are resolved.

**Comment by LarsVoelker** [comment]
The module "parser" in python was deprecated and removed. So this was resolved by itself.

P.S. I renamed the class as well, if someone wants to use an outdated python, which nobody should do.
